### ISSUE TITLE
Sheet Comes in as CSV with One Observation

### ISSUE THREAD

**Issue by KatieOlson11** [elias-jhsph/rsmartsheet#2]
I’m using get_sheet_as_csv to pull from Smartsheets. It’s bringing in the correct sheet, but it’s all jumbled as one observation of one variable. I’ve tried converting it to a tibble with no luck. Any ideas?
See sample screen shot.
![image](https://github.com/elias-jhsph/rsmartsheet/assets/45111298/56cbf474-8dfb-4354-b9e7-3075ab8ae54d)

**Comment by eliaswestonfarber** [comment]
Ok I am happy to give you advice with this! This isn't and issue with the package, the trick here is that get_sheet_as_csv is a function that returns the raw csv data (which is exactly what you have shown) what you probably want is a data frame. All you have to do is parse that data into a data frame. I would recommend using read_csv from the tidyverse. You can simply do something like...

```
data <- read_csv(get_sheet_as_csv("Test... TODO FILL IN"))
```

Does that work?

**Comment by KatieOlson11** [comment]
It does! Thank you so much. I really needed this package in my life.
