### ISSUE TITLE
Attachment Download

### ISSUE THREAD

**Issue by KatieOlson11** [elias-jhsph/rsmartsheet#3]
Hello, Not sure if this is an actual issue, or I'm just using it wrong. I have a Smartsheet with several jpg attachments. I'd like to download them all into one folder. I'm using download_sheet_attachment("[my smartsheet name here]", "[the name of the folder i'd like them to go into]"). I've also tried it by including the specific name of the attachment with the name of the folder I'd like them to go into. In all cases, I get this error:
Error in GET(paste("https://api.smartsheet.com/2.0/sheets", id, "attachments",  : 
  could not find function "GET"
What am I doing wrong?

**Comment by eliaswestonfarber** [comment]
you needs to specify the name of the attachment if it is not the same name as the sheet

download_sheet_attachment("sheet_name","a_folder/maybe_another_folder/sheet_name.csv", file_name="the_name_of_the_attachment")

**Comment by KatieOlson11** [comment]
So, I can only download one attachment at a time? If there are multiple, I can't have it just download all of the attachments of a sheet?

**Comment by eliaswestonfarber** [comment]
Correct you can’t
________________________________
